### ISSUE TITLE
没看懂怎么用 能教教吗

### ISSUE THREAD

**Issue by AlabasterStone** [Gtd232/EasyIP#1]

**Comment by Gtd232** [comment]
az这是一个基于flask做的东西，也算是我练习的吧。你只要找到一个你可以用的服务器，安装好python和flask，然后运行main.py，如果需要内网穿透就用内网穿透，然后通过内网穿透后的网址配上端口号来访问。有点烦，你可以去pythonanywhere上部署，虽有限制但是免费，等下我找点东西。

**Comment by AlabasterStone** [comment]
不是需要嵌入图片吗

**Comment by Gtd232** [comment]
是以嵌入图片的方式获取访问者ip的

**Comment by Gtd232** [comment]
*A营图床，加载较慢*  
去https://www.pythonanywhere.com/  
点![](https://asset.gitblock.cn/Media?name=D9EFC4ED110912BA22706F7C4BD1C9F4.png)  
点![](https://asset.gitblock.cn/Media?name=0B6581D2B86EF6D1A08908CAD6F44AD2.png)  

然后注册不多说了  
点![](https://asset.gitblock.cn/Media?name=BFE8F848DD978D295411D77F90DEA85A.png)  
点![](https://asset.gitblock.cn/Media?name=129ED0558CCBD33842DA2AF511813D92.png)  
点next，点flask，点python3.6，点next  
上面就是让你选python为3.6的版本，用flask。  
点击上面一栏的Files，然后跳出来的就是很多文件和目录。  
左边的目录选mysite/，然后跳出来的新网页就是相关目录下的文件，点那个flask_app.py  
新网页就是编辑你的那个文件，把里面内容删了，然后把我写的main.py复制进去，注意pythonanywhere太奇妙了要修改点东西，当然你也可以自己写  
也可以直接复制如下内容，不用修改了：  
```python
from flask import Flask, request
from time import strftime, localtime
from os import getcwd, mkdir
import urllib.request

p = getcwd()
try:
    mkdir(p + '/Get_IP/')
except FileExistsError:
    pass
try:
    mkdir(p + '/Get_IP/logs/')
except FileExistsError:
    pass

app = Flask(__name__)


@app.route('/api/Get/IP')
def get_ip():  # 虽然感觉用大写好点，但编辑器还是推荐我用小写/滑稽
    # 如果使用Nginx，请使用以下代码：
    """
    ip = request.headers['X-Forwarded-For']
    """
    ip = request.headers['X-Forwarded-For']
    response = urllib.request.urlopen('http://ip-api.com/json/' + ip).read().decode('utf-8')
    if bool(request.args.get('id')):
        with open('./Get_IP/logs/' + request.args.get('id') + '.log', 'a', encoding='ASCII') as f:
            f.write(strftime('%Y-%m-%d %H:%M:%S', localtime()) + '  ' + ip + response + '\n')
        return ip
    else:
        return '唔唔唔你知不知你没加参数唔唔唔'



@app.route('/api/See/IP')
def see_ip():  # 虽然感觉用大写好点，但编辑器还是推荐我用小写/滑稽
    # 如果使用Nginx，请使用以下代码：
    """
    ip = request.headers['X-Forwarded-For']
    """

    if bool(request.args.get('id')):
        with open('./Get_IP/logs/' + request.args.get('id') + '.log', 'r', encoding='ASCII') as f:
            fi = f.read()
        return fi
    else:
        return '唔唔唔你知不知你没加参数唔唔唔'

```  
然后点save，等圈圈不转了哦哦哦  


点右上角那个奇妙按钮中的web   
![](https://asset.gitblock.cn/Media?name=3828A1889702F88B882EA6F2A6023C67.png)  

点![](https://asset.gitblock.cn/Media?name=732CB95D121B7BB0E55A9AE129EB437B.png)等圈圈没有就能用了  

记得每隔两三个月点![](https://asset.gitblock.cn/Media?name=732CB95D121B7BB0E55A9AE129EB437B.png)除非你付费  
通过markdown放`![](//你的用户名.pythonanywhere.com/api/Get/IP?id=xxx)`xxx换成随便一个，特别点，比如485676这种，记住就行哦哦哦  
来这里看`https://你的用户名.pythonanywhere.com/api/See/IP?id=xxx`  
你也可以在pythonanywhere的后台看，在Files里左边目录Get_IP点进去，左边再点logs，右边就是全部文件了  
**注意法律问题，使用本工具带来的后果自负唔唔唔**

**Comment by AlabasterStone** [comment]
谢谢 我试试 唔唔唔

**Comment by AlabasterStone** [comment]
> 

woc NB

**Comment by Gtd232** [comment]
唔唔唔 使用本工具带来的后果自负哦哦哦
